import { Block }                         from "./blocks/0/Block";
import { Spike }                         from "./blocks/1/Spike";
import { Checkpoint }                    from "./blocks/2/Checkpoint";
import { Ice }                           from "./blocks/3/Ice";
import { Refresher }                     from "./blocks/4/Refresher";
import { Trampoline }                    from "./blocks/5/Trampoline";
import { DisappearingBlock }             from "./blocks/6/DisappearingBlock";
import { Sand }                          from "./blocks/7/Sand";
import { Space }                         from "./blocks/8/Space";
import { RoundTrampoline }               from "./blocks/9/RoundTrampoline";
import { NonHookableSpike }              from "./blocks/10/NonHookableSpike";
import { TogglingBlock }                 from "./blocks/11/TogglingBlock";
import { Rotator }                       from "./blocks/12/Rotator";
import { AllDirectionMovableBlock }      from "./blocks/13/AllDirectionMovableBlock";
import { OneDirectionMovableBlock }      from "./blocks/14/OneDirectionMovableBlock";
import { TiltBlock }                     from "./blocks/15/TiltBlock";
import { TouchBlock }                    from "./blocks/16/TouchBlock";
import { TextBlock }                     from "./blocks/17/TextBlock";
import { Key }                           from "./blocks/18/Key";
import { Lock }                          from "./blocks/19/Lock";
import { Square }                        from "./blocks/20/Square";
import { Circle }                        from "./blocks/21/Circle";
import { Slope }                         from "./blocks/22/Slope";
import { FlyModeBlock }                  from "./blocks/23/FlyModeBlock";
import { Conveyor }                      from "./blocks/24/Conveyor";
import { NoteBlock }                     from "./blocks/25/NoteBlock";
import { BlockWithPhysics }              from "./blocks/26/BlockWithPhysics";
import { Bridge }                        from "./blocks/27/Bridge";
import { Bull }                          from "./blocks/28/Bull";
import { Letter }                        from "./blocks/29/Letter";
import { NonHookableBlock }              from "./blocks/30/NonHookableBlock";
import { Glass }                         from "./blocks/31/Glass";
import { SmallSpikes }                   from "./blocks/32/SmallSpikes";
import { BackGroundBlock }               from "./blocks/33/BackGroundBlock";
import { GlassImage }                    from "./blocks/34/GlassImage";
import { SpikeImage }                    from "./blocks/35/SpikeImage";
import { BlockImage }                    from "./blocks/36/BlockImage";
import { Trigger }                       from "./blocks/37/Trigger";
import { ObjectStateSetter }             from "./blocks/38/ObjectStateSetter";
import { Mover }                         from "./blocks/39/Mover";
import { CircleWithPhysics }             from "./blocks/40/CircleWithPhysics";
import { ObjectPosSetter }               from "./blocks/41/ObjectPosSetter";
import { ObjectAngleSetter }             from "./blocks/42/ObjectAngleSetter";
import { ObjectParamSetter }             from "./blocks/43/ObjectParamSetter";
import { ObjectColorSetter }             from "./blocks/44/ObjectColorSetter";
import { ObjectMoveSpeedSetter }         from "./blocks/45/ObjectMoveSpeedSetter";
import { ObjectRotationSpeedSetter }     from "./blocks/46/ObjectRotationSpeedSetter";
import { PauseTrigger }                  from "./blocks/47/PauseTrigger";
import { Robot }                         from "./blocks/48/Robot";
import { DangerousRobot }                from "./blocks/49/DangerousRobot";
import { BodyDirectionGuide }            from "./blocks/50/BodyDirectionGuide";
import { BodyWitnNoPhysics }             from "./blocks/51/BodyWitnNoPhysics";
import { GradientImage }                 from "./blocks/52/GradientImage";
import { NoHeroZone }                    from "./blocks/53/NoHeroZone";
import { Portal }                        from "./blocks/54/Portal";
import { CameraMinMax }                  from "./blocks/55/CameraMinMax";
import { CameraSize }                    from "./blocks/56/CameraSize";
import { CameraTarget }                  from "./blocks/57/CameraTarget";
import { AbilityAdder }                  from "./blocks/58/AbilityAdder";
import { AbilityRemover }                from "./blocks/59/AbilityRemover";
import { ShadowBlock }                   from "./blocks/60/ShadowBlock";
import { DiscoloredBlock }               from "./blocks/61/DiscoloredBlock";
import { HistoryBackGroundSquares }      from "./blocks/62/HistoryBackGroundSquares";
import { DiscoloredBackGroundSquares }   from "./blocks/63/DiscoloredBackGroundSquares";
import { GrayGlassImage }                from "./blocks/64/GrayGlassImage";
import { GraySmallGlassesImage }         from "./blocks/65/GraySmallGlassesImage";
import { Grave }                         from "./blocks/66/Grave";
import { Looper }                        from "./blocks/67/Looper";
import { Historian }                     from "./blocks/68/Historian";
import { QwessBot }                      from "./blocks/69/QwessBot";
import { RandomTrigger }                 from "./blocks/70/RandomTrigger";
import { TimeScale }                     from "./blocks/71/TimeScale";
import { SkyColorSetter }                from "./blocks/72/SkyColorSetter";
import { Magnet }                        from "./blocks/73/Magnet";
import { GravityPowerSetter }            from "./blocks/74/GravityPowerSetter";
import { EventTrigger }                  from "./blocks/75/EventTrigger";
import { KillZone }                      from "./blocks/76/KillZone";
import { Moss }                          from "./blocks/77/Moss";
import { Impulse }                       from "./blocks/78/Impulse";
import { ToggleTrigger }                 from "./blocks/79/ToggleTrigger";
import { SuperTile }                     from "./blocks/80/SuperTile";
import { PulseTrigger }                  from "./blocks/81/PulseTrigger";
import { IFGround }                      from "./blocks/82/IFGround";
import { ObjectRelativePosSetter }       from "./blocks/83/ObjectRelativePosSetter";


import { BasicBlock }                    from "./classes/abstract/BasicBlock";

export * from "./blocks/0/Block";
export * from "./blocks/1/Spike";
export * from "./blocks/2/Checkpoint";
export * from "./blocks/3/Ice";
export * from "./blocks/4/Refresher";
export * from "./blocks/5/Trampoline";
export * from "./blocks/6/DisappearingBlock";
export * from "./blocks/7/Sand";
export * from "./blocks/8/Space";
export * from "./blocks/9/RoundTrampoline";
export * from "./blocks/10/NonHookableSpike";
export * from "./blocks/11/TogglingBlock";
export * from "./blocks/12/Rotator";
export * from "./blocks/13/AllDirectionMovableBlock";
export * from "./blocks/14/OneDirectionMovableBlock";
export * from "./blocks/15/TiltBlock";
export * from "./blocks/16/TouchBlock";
export * from "./blocks/17/TextBlock";
export * from "./blocks/18/Key";
export * from "./blocks/19/Lock";
export * from "./blocks/20/Square";
export * from "./blocks/21/Circle";
export * from "./blocks/22/Slope";
export * from "./blocks/23/FlyModeBlock";
export * from "./blocks/24/Conveyor";
export * from "./blocks/25/NoteBlock";
export * from "./blocks/26/BlockWithPhysics";
export * from "./blocks/27/Bridge";
export * from "./blocks/28/Bull";
export * from "./blocks/29/Letter";
export * from "./blocks/30/NonHookableBlock";
export * from "./blocks/31/Glass";
export * from "./blocks/32/SmallSpikes";
export * from "./blocks/33/BackGroundBlock";
export * from "./blocks/34/GlassImage";
export * from "./blocks/35/SpikeImage";
export * from "./blocks/36/BlockImage";
export * from "./blocks/37/Trigger";
export * from "./blocks/38/ObjectStateSetter";
export * from "./blocks/39/Mover";
export * from "./blocks/40/CircleWithPhysics";
export * from "./blocks/41/ObjectPosSetter";
export * from "./blocks/42/ObjectAngleSetter";
export * from "./blocks/43/ObjectParamSetter";
export * from "./blocks/44/ObjectColorSetter";
export * from "./blocks/45/ObjectMoveSpeedSetter";
export * from "./blocks/46/ObjectRotationSpeedSetter";
export * from "./blocks/47/PauseTrigger";
export * from "./blocks/48/Robot";
export * from "./blocks/49/DangerousRobot";
export * from "./blocks/50/BodyDirectionGuide";
export * from "./blocks/51/BodyWitnNoPhysics";
export * from "./blocks/52/GradientImage";
export * from "./blocks/53/NoHeroZone";
export * from "./blocks/54/Portal";
export * from "./blocks/55/CameraMinMax";
export * from "./blocks/56/CameraSize";
export * from "./blocks/57/CameraTarget";
export * from "./blocks/58/AbilityAdder";
export * from "./blocks/59/AbilityRemover";
export * from "./blocks/60/ShadowBlock";
export * from "./blocks/61/DiscoloredBlock";
export * from "./blocks/62/HistoryBackGroundSquares";
export * from "./blocks/63/DiscoloredBackGroundSquares";
export * from "./blocks/64/GrayGlassImage";
export * from "./blocks/65/GraySmallGlassesImage";
export * from "./blocks/66/Grave";
export * from "./blocks/67/Looper";
export * from "./blocks/68/Historian";
export * from "./blocks/69/QwessBot";
export * from "./blocks/70/RandomTrigger";
export * from "./blocks/71/TimeScale";
export * from "./blocks/72/SkyColorSetter";
export * from "./blocks/73/Magnet";
export * from "./blocks/74/GravityPowerSetter";
export * from "./blocks/75/EventTrigger";
export * from "./blocks/76/KillZone";
export * from "./blocks/77/Moss";
export * from "./blocks/78/Impulse";
export * from "./blocks/79/ToggleTrigger";
export * from "./blocks/80/SuperTile";
export * from "./blocks/81/PulseTrigger";
export * from "./blocks/82/IFGround";
export * from "./blocks/83/ObjectRelativePosSetter";

export * from "./classes/real/Appearance";
export * from "./classes/real/Movement";
export * from "./classes/real/TRMap";
export * from "./classes/real/Vector2";

export const BLOCKS_WITH_IDS: (typeof BasicBlock)[] = [
	Block, Spike, Checkpoint, Ice, Refresher, Trampoline, DisappearingBlock, Sand, Space, RoundTrampoline, // 0X
	NonHookableSpike, TogglingBlock, Rotator, AllDirectionMovableBlock, OneDirectionMovableBlock, TiltBlock, TouchBlock, TextBlock, Key, Lock, // 1X
	Square, Circle, Slope, FlyModeBlock, Conveyor, NoteBlock, BlockWithPhysics, Bridge, Bull, Letter, // 2X
	NonHookableBlock, Glass, SmallSpikes, BackGroundBlock, GlassImage, SpikeImage, BlockImage, Trigger, ObjectStateSetter, Mover, // 3X
	CircleWithPhysics, ObjectPosSetter, ObjectAngleSetter, ObjectParamSetter, ObjectColorSetter, ObjectMoveSpeedSetter, ObjectRotationSpeedSetter, PauseTrigger, Robot, DangerousRobot, // 4X
	BodyDirectionGuide, BodyWitnNoPhysics, GradientImage, NoHeroZone, Portal, CameraMinMax, CameraSize, CameraTarget, AbilityAdder, AbilityRemover, // 5X
	ShadowBlock, DiscoloredBlock, HistoryBackGroundSquares, DiscoloredBackGroundSquares, GrayGlassImage, GraySmallGlassesImage, Grave, Looper, Historian, QwessBot, // 7X
	RandomTrigger, TimeScale, SkyColorSetter, Magnet, GravityPowerSetter, EventTrigger, KillZone, Moss, Impulse, ToggleTrigger, // 7X
	SuperTile, PulseTrigger, IFGround, ObjectRelativePosSetter // 7X
];
